### PR TITLE
Update 3.0.0

### LINKED ISSUE #2: Vulnerability
```sh
                       === npm audit security report ===

# Run  npm update xhr-request --depth 2  to resolve 1 vulnerability

  High            Regular Expression Denial of Service

  Package         minimatch

  Dependency of   nice-color-palettes [dev]

  Path            nice-color-palettes > xhr-request > buffer-to-arraybuffer >
                  tape > glob > minimatch

  More info       https://nodesecurity.io/advisories/118
```

### PR DESCRIPTION
**Pull request by mattdesl**
- Updates to latest palettes as of Oct 14 2018
- Include a visualization sketch and new image generator
- Replace `xhr-request` with `got` to fix #2 

Any chance you can give me push access @jmckinnell ? :smile:

### CODE REVIEW

**Comment by neo** [comment]
cc: @iranreyes ^

**Comment by mattdesl** [comment]
bump 👋

**Comment by iranreyes** [comment]
Added you back to the repo @mattdesl

**Comment by mattdesl** [comment]
Thanks!

**Pull request merged**
